spring.application.name=inventory-saas

spring.datasource.url=jdbc:mysql://localhost:3306/inventory_saas
spring.datasource.username=root
spring.datasource.password=SuaSenhaAqui

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
